name: drift_macros
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-0

# Add regular dependencies here.
dependencies:
  macros: ^0.1.0-main.5
  drift: ^2.18.0
  drift_dev: ^2.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
