name: docs
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  web: ^1.0.0
  code_snippets:
    hosted: https://simonbinder.eu
    version: ^0.0.13

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.10
  lints: ^3.0.0
  sass_builder: ^2.2.1
  built_site:
    hosted: https://simonbinder.eu
    version: ^0.2.17

dependency_overrides:
  built_site:
    path: /home/simon/src/built_site/built_site
